/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.EnterPrise.EnterPrise;
import Business.NetWork.NetWork;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author pruth
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,
    EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer=userProcessContainer;
        populateTree();
    }
    
    public void populateTree()
    {
      DefaultTreeModel dtm = (DefaultTreeModel) jTree.getModel();

        ArrayList<NetWork> networkList = system.getNetworkList();
        ArrayList<EnterPrise> enterpriseList;
        ArrayList<Organization> organizationList;

        NetWork network;
        EnterPrise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;

        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);

            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);

                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);

                }
            }
        }
        dtm.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        selectedNodeJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageNetworkJBtn = new javax.swing.JButton();
        manageEnterpriseJBtn = new javax.swing.JButton();
        manageEnterPriseAdmin = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(null);

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTree);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 0, 140, 410);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel1.setLayout(null);

        selectedNodeJLabel.setText("<View Selected Node>");
        jPanel1.add(selectedNodeJLabel);
        selectedNodeJLabel.setBounds(250, 30, 220, 30);

        jLabel2.setText("Selected Node");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 30, 100, 30);

        manageNetworkJBtn.setText("Manage Network");
        manageNetworkJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageNetworkJBtn);
        manageNetworkJBtn.setBounds(180, 100, 170, 30);

        manageEnterpriseJBtn.setText("Manage Enterprise");
        manageEnterpriseJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageEnterpriseJBtn);
        manageEnterpriseJBtn.setBounds(180, 150, 170, 30);

        manageEnterPriseAdmin.setText("Manage EnterpriseAdmin");
        manageEnterPriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterPriseAdminActionPerformed(evt);
            }
        });
        jPanel1.add(manageEnterPriseAdmin);
        manageEnterPriseAdmin.setBounds(180, 210, 220, 30);

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJBtnActionPerformed
        ManageNetworkJPanel manageNetWorkJPanel = new ManageNetworkJPanel(userProcessContainer,system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", manageNetWorkJPanel);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageNetworkJBtnActionPerformed

    private void manageEnterpriseJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJBtnActionPerformed
       ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer,system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", manageEnterpriseJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJBtnActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
       DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
       if(selectedNode != null)
       {
           selectedNodeJLabel.setText(selectedNode.toString());
       }
    }//GEN-LAST:event_jTreeValueChanged

    private void manageEnterPriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterPriseAdminActionPerformed
           ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer,system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", manageEnterpriseAdminJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterPriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JButton manageEnterPriseAdmin;
    private javax.swing.JButton manageEnterpriseJBtn;
    private javax.swing.JButton manageNetworkJBtn;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
