/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.DistributorRole;

import Business.WorkQueue.VaccineRequest;
import javax.swing.JPanel;

/**
 *
 * @author pruth
 */
public class ProcessDistributionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessDistributionJPanel
     */
    JPanel userProcessContainer;
    VaccineRequest request;
    public ProcessDistributionJPanel(JPanel userProcessContainer,VaccineRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        submitJButton1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Comment :");
        add(jLabel1);
        jLabel1.setBounds(38, 47, 110, 20);
        add(resultJTextField);
        resultJTextField.setBounds(154, 44, 140, 30);

        submitJButton1.setText("Delivered");
        submitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButton1ActionPerformed(evt);
            }
        });
        add(submitJButton1);
        submitJButton1.setBounds(80, 110, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButton1ActionPerformed
        
        request.setStatus("Delivered");
    }//GEN-LAST:event_submitJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton1;
    // End of variables declaration//GEN-END:variables
}
