/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.ProviderRole;

import Business.EcoSystem;
import Business.EnterPrise.EnterPrise;
import Business.Organization.ProviderOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pruth
 */
public class ProviderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ProviderOrganization organization;
    private EnterPrise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    public ProviderWorkAreaJPanel(JPanel userProcessContainer, ProviderOrganization organization , EnterPrise enterprise, UserAccount userAccount,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system= system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendRequestBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();

        setLayout(null);

        sendRequestBtn.setText("Send Request");
        sendRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestBtnActionPerformed(evt);
            }
        });
        add(sendRequestBtn);
        sendRequestBtn.setBounds(510, 160, 140, 40);

        orderBtn.setText("Accept order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        add(orderBtn);
        orderBtn.setBounds(280, 160, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestBtnActionPerformed
       OrderRequestForHospital orderRequestForHospital = new OrderRequestForHospital(userProcessContainer,organization,enterprise,userAccount,system);
        userProcessContainer.add("processWorkRequestJPanel", orderRequestForHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendRequestBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        AcceptOrderJPanel acceptOrderJPanel = new AcceptOrderJPanel(userProcessContainer,organization,userAccount,system);
        userProcessContainer.add("acceptOrderJPanel", acceptOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton sendRequestBtn;
    // End of variables declaration//GEN-END:variables
}
