/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aravind
 */
public class ManageFlightMain extends javax.swing.JPanel {
private JPanel mainpageRight;
    private TravelAgency  travelagency;
    private Airliner airliner;
    /**
     * Creates new form ManageFlightMain
     */
   

    ManageFlightMain(JPanel MainpageRight, TravelAgency travelagency) {
         initComponents();
          this.mainpageRight= MainpageRight;
        this.travelagency= travelagency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinerNameLabel = new javax.swing.JLabel();
        airlineNameTxtBox = new javax.swing.JTextField();
        createFlightBtn = new javax.swing.JButton();

        airlinerNameLabel.setText("AirlinerName");

        airlineNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineNameTxtBoxActionPerformed(evt);
            }
        });

        createFlightBtn.setText("create flight");
        createFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(airlinerNameLabel)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createFlightBtn)
                    .addComponent(airlineNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlineNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(createFlightBtn)
                .addContainerGap(283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlineNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineNameTxtBoxActionPerformed

    private void createFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightBtnActionPerformed
    //JPanel MainpageRight;

        CreateNewFlight panel2 = new CreateNewFlight(mainpageRight, travelagency);
        mainpageRight.add("CreateNewFlight", panel2);
        CardLayout layout = (CardLayout)mainpageRight.getLayout();
        layout.next(mainpageRight);

        // TODO add your handling code here:
    }//GEN-LAST:event_createFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineNameTxtBox;
    private javax.swing.JLabel airlinerNameLabel;
    private javax.swing.JButton createFlightBtn;
    // End of variables declaration//GEN-END:variables
}
