/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravind
 */
public class ManageAirlinerMain extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerMain
     */
    private JPanel MainpageRight;
    private TravelAgency travelagency;
    public ManageAirlinerMain(JPanel MainpageRight, TravelAgency travelagency) {
        initComponents();
        this.MainpageRight=MainpageRight;
        this.travelagency= travelagency;
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAirlinerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Airlinenametable = new javax.swing.JTable();
        createAirlinerBtn = new javax.swing.JButton();
        createFlightBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANAGE AIRLINERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        manageAirlinerBtn.setText("View Airliner");
        add(manageAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Airlinernamae", "Modelno", "Manufacturwer", "YearofMake"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 380, 200));

        Airlinenametable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Airlinenametable);
        if (Airlinenametable.getColumnModel().getColumnCount() > 0) {
            Airlinenametable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 150, 140));

        createAirlinerBtn.setText("Manage Flights");
        createAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerBtnActionPerformed(evt);
            }
        });
        add(createAirlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        createFlightBtn.setText("create flight");
        createFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightBtnActionPerformed(evt);
            }
        });
        add(createFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerBtnActionPerformed
     ManageFlightMain panel1 = new ManageFlightMain(MainpageRight, travelagency);
     MainpageRight.add("CreateNewAirliner", panel1);
     CardLayout layout = (CardLayout)MainpageRight.getLayout();
        layout.next(MainpageRight);
        // TODO add your handling code here:
    }//GEN-LAST:event_createAirlinerBtnActionPerformed

    private void createFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightBtnActionPerformed
     
        
        CreateNewFlight panel2 = new CreateNewFlight(MainpageRight, travelagency);
     MainpageRight.add("CreateNewFlight", panel2);
     CardLayout layout = (CardLayout)MainpageRight.getLayout();
        layout.next(MainpageRight);

        // TODO add your handling code here:
    }//GEN-LAST:event_createFlightBtnActionPerformed
 public void populatetable()
 {
 DefaultTableModel dtm = (DefaultTableModel)Airlinenametable.getModel();
    dtm.setRowCount(0);
    
    for(Airliner airliner:travelagency.getAirlinerlist())
    {
    Object[] obj = new Object[1];
    obj[0]=airliner;
    dtm.addRow(obj);
    }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Airlinenametable;
    private javax.swing.JButton createAirlinerBtn;
    private javax.swing.JButton createFlightBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton manageAirlinerBtn;
    // End of variables declaration//GEN-END:variables
}
