/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.SystemAdminWorkArea;

import Business.Disease.Disease;
import Business.EcoSystem;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravind
 */
public class ManageDiseaseandVaccine extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiseaseandVaccine
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    public ManageDiseaseandVaccine(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system =system;
        this.userProcessContainer = userProcessContainer;
        populateTable();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        addBtn.setVisible(false);
        diseaseName.setVisible(false);
        diseaseSym.setVisible(false);
        diseaseVaccineTbl.setVisible(false);
        vaccineName.setVisible(false);
        expiryDate.setVisible(false);
        stockAvai.setVisible(false);
        updateBtn.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diseaseSym = new javax.swing.JTextField();
        vaccineName = new javax.swing.JTextField();
        stockAvai = new javax.swing.JTextField();
        diseaseName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        expiryDate = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diseaseVaccineTbl = new javax.swing.JTable();
        newBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Disease Symptom :");
        add(jLabel1);
        jLabel1.setBounds(360, 330, 100, 30);

        jLabel2.setText("Vaccine :");
        add(jLabel2);
        jLabel2.setBounds(110, 320, 43, 14);

        jLabel3.setText("Disease Name:");
        add(jLabel3);
        jLabel3.setBounds(250, 280, 90, 30);

        jLabel4.setText("Stocks Available :");
        add(jLabel4);
        jLabel4.setBounds(360, 380, 90, 30);
        add(diseaseSym);
        diseaseSym.setBounds(490, 330, 100, 30);
        add(vaccineName);
        vaccineName.setBounds(190, 320, 100, 30);

        stockAvai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAvaiActionPerformed(evt);
            }
        });
        add(stockAvai);
        stockAvai.setBounds(490, 380, 100, 30);
        add(diseaseName);
        diseaseName.setBounds(360, 280, 100, 30);

        jLabel5.setText("Expiry Date :");
        add(jLabel5);
        jLabel5.setBounds(100, 380, 63, 30);

        expiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateActionPerformed(evt);
            }
        });
        add(expiryDate);
        expiryDate.setBounds(190, 380, 100, 30);

        addBtn.setText("Add");
        add(addBtn);
        addBtn.setBounds(320, 440, 80, 30);

        diseaseVaccineTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disease Name", "Disease Symptom", "Vaccine", "Expiry Date ", "Stock"
            }
        ));
        jScrollPane1.setViewportView(diseaseVaccineTbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 790, 160);

        newBtn.setText("New");
        add(newBtn);
        newBtn.setBounds(560, 240, 70, 30);

        updateBtn.setText("Update");
        add(updateBtn);
        updateBtn.setBounds(320, 440, 80, 30);

        editBtn.setText("Edit");
        add(editBtn);
        editBtn.setBounds(650, 240, 70, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void stockAvaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockAvaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockAvaiActionPerformed

    private void expiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField diseaseName;
    private javax.swing.JTextField diseaseSym;
    private javax.swing.JTable diseaseVaccineTbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField expiryDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField stockAvai;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField vaccineName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)diseaseVaccineTbl.getModel();
        
        model.setRowCount(0);
        
       
      for(Vaccine v :system.getVaccineCatalog().getVaccineList()){
        for(Disease d:system.getDiseaseCatalog().getDiseaseList()){
            
        
               if(d.getVaccineSugg() == v.getVaccineId())
               {
                Object[] row = new Object[5];
                row[0] = d.getDiseaseName();
                row[1] = d.getDiagnosis();
                row[2] = v.getVaccineName();
                row[3] = v.getExpiryDate();
                row[4] = v.getStockAvalilable();

                model.addRow(row);
               }
           }
        }
    }
}
