/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Aeroplane;
import Business.Aeroplanelist;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aravind
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
private Aeroplanelist al;
    public ViewJPanel(Aeroplanelist al) {
       initComponents();
       this.al = al;
       addintoTable();
       
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
public void addintoTable()
{
    DefaultTableModel dtm = (DefaultTableModel)ViewupdateTable.getModel();
    dtm.setRowCount(0);
    
    for(Aeroplane a: al.getAirplanelist())
     
        { Object row[] = new Object[15];
          row[0] = a;
          row[1] = a.getAirlinename();
          row[2] = a.getMaintanenceStatus();
          row[3] = a.getManufacturerName();
          row[4] = a.getAirportName();
          row[5] = a.getAvailableStatus();
          row[6] = a.getNoofseats();
          row[7] = a.getYearofManufacture();
          row[8] = a.getModelno();
          row[9] = a.getSerialNumber();
          
           dtm.addRow(row);
        }
          
    
      int selectedrow = ViewupdateTable.getSelectedRow();
       
       
      // else
           
    
        
        }       
        
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        MaintanenceCertificateTxtbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AvailableStatustxtbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ModelNotextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AirlineNameTxtBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SerialNoTxtBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AvailableSeatsTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AirportNameTxtBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MfgNameTxtbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MfgYearTxtBox = new javax.swing.JTextField();
        ViewBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewupdateTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("Available Seats :");

        jLabel4.setText("Serial No :");

        jLabel5.setText("Airline :");

        jLabel6.setText("Airport :");

        jLabel7.setText("Manufacture Year :");

        jLabel8.setText("Maintanence Certificate :");

        jLabel9.setText("Available Status");

        jLabel1.setText("Manufacturer :");

        MfgNameTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfgNameTxtboxActionPerformed(evt);
            }
        });

        jLabel2.setText("Model No");

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        ViewupdateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial No", "Airline Name", "Maintanance Status", "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ViewupdateTable);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("View and Update Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewBtn)
                .addGap(65, 65, 65)
                .addComponent(UpdateBtn)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaintanenceCertificateTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MfgNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AirportNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AvailableSeatsTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SerialNoTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AirlineNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MfgYearTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModelNotextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(60, 60, 60)
                                    .addComponent(AvailableStatustxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(MfgNameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AvailableSeatsTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SerialNoTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(AirlineNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AirportNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MfgYearTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ModelNotextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(AvailableStatustxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(MaintanenceCertificateTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBtn)
                    .addComponent(UpdateBtn))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MfgNameTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfgNameTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MfgNameTxtboxActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
      int selectedrow=ViewupdateTable.getSelectedRow();
        if(selectedrow >=0)
       {
        
           Aeroplane aep = (Aeroplane)ViewupdateTable.getValueAt(selectedrow, 0);
         AirlineNameTxtBox.setText(String.valueOf(aep.getAirlinename()));
         AirportNameTxtBox.setText(String.valueOf(aep.getAirportName()));
         AvailableSeatsTxtBox.setText(String.valueOf(aep.getNoofseats()));
         AvailableStatustxtbox.setText(String.valueOf(aep.getAvailableStatus()));
          MaintanenceCertificateTxtbox.setText(String.valueOf(aep.getMaintanenceStatus()));
         
          MfgNameTxtbox.setText(String.valueOf(aep.getManufacturerName()));
         SerialNoTxtBox.setText(String.valueOf(aep.getSerialNumber()));
          MfgYearTxtBox.setText(String.valueOf(aep.getYearofManufacture()));
          ModelNotextBox.setText(String.valueOf(aep.getModelno()));
       } 
       else
       {
          JOptionPane.showMessageDialog(null,"Select any row");     
       }
// txtBloodPressure.setText(String.valueOf(vs.getBloodPressure()));
           
       


        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed

     
    DefaultTableModel dtm = (DefaultTableModel)ViewupdateTable.getModel();
    int rowselect = ViewupdateTable.getSelectedRow();
      if(rowselect >=0)
      {
          Aeroplane aep = (Aeroplane)ViewupdateTable.getValueAt(rowselect,0);
          al.deleteValues(aep);
           
          Aeroplane apn = al.addAeroplanes();
          
          apn.setAirlinename(AirlineNameTxtBox.getText());
          apn.setAirportName(AirportNameTxtBox.getText());
          apn.setAvailableStatus(AvailableStatustxtbox.getText());
          apn.setMaintanenceStatus(MaintanenceCertificateTxtbox.getText());
          apn.setManufacturerName(MfgNameTxtbox.getText());
          apn.setModelno(ModelNotextBox.getText());
          apn.setNoofseats(Integer.parseInt(AvailableSeatsTxtBox.getText()));
          apn.setSerialNumber(Integer.parseInt(SerialNoTxtBox.getText()));
          apn.setYearofManufacture(Integer.parseInt(MfgYearTxtBox.getText()));
      }
      addintoTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirlineNameTxtBox;
    private javax.swing.JTextField AirportNameTxtBox;
    private javax.swing.JTextField AvailableSeatsTxtBox;
    private javax.swing.JTextField AvailableStatustxtbox;
    private javax.swing.JTextField MaintanenceCertificateTxtbox;
    private javax.swing.JTextField MfgNameTxtbox;
    private javax.swing.JTextField MfgYearTxtBox;
    private javax.swing.JTextField ModelNotextBox;
    private javax.swing.JTextField SerialNoTxtBox;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JTable ViewupdateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
   
}
